// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type CurrentWallpaper struct {
	ID    int64
	Path  string
	SetAt time.Time
}

type WallpaperHistory struct {
	ID      int64
	Path    string
	SetAt   time.Time
	UnsetAt *time.Time
}
